# Branch Protection Rules Configuration
# File: .github/branch-protection-rules.yml

# Main/Master Branch Protection
master:
  protection:
    required_status_checks:
      strict: true
    
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 2
      
    restrictions:
      apps: []
      users: []
      teams: ["devops-team", "senior-developers"]
      
    enforce_admins: true
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false

# Branch Naming Pattern (to be enforced via pre-commit hook or GitHub Actions)
branch_naming_pattern:
  pattern: '^(feature|bugfix|hotfix|release)/E1901-\d{4}-[a-z0-9-]+$'
  examples:
    - feature/JIRA-123-user-authentication
    - bugfix/PROJ-456-fix-memory-leak
    - hotfix/PROD-789-critical-security-patch
    - release/REL-234-version-2-1-0

# Branch Types and Their Usage
branch_types:
  feature:   # New features and non-emergency fixes
    prefix: feature/
    base: develop
  
  bugfix:    # Bug fixes that are not urgent
    prefix: bugfix/
    base: develop
    
  hotfix:    # Urgent fixes for production
    prefix: hotfix/
    base: master
    
  release:   # Release preparation branches
    prefix: release/
    base: develop